# Load data and analysis results generated by
# manuscript_kernel.R
load("manuscript.RData")

capture.output(summary(partition_map_global), file = "part_map_glob.csv")
partition_map_global_df = data.frame(partition_map_global)
write.table(partition_map_global_df,'part_map_glob.csv',sep='\t')

lapply(partition_map_global, function(x) write.table( data.frame(x), 'part_map_glob.csv'  , append= T, sep=',' )