echo phylips/Borowiec2015_Best108.phy; ../scripts/phylippart2multifasta.py -p phylips/Borowiec2015_Best108 -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Borowiec2015_Total1080.phy; ../scripts/phylippart2multifasta.py -p phylips/Borowiec2015_Total1080 -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Chang2015_Chang2015.phy; ../scripts/phylippart2multifasta.py -p phylips/Chang2015_Chang2015 -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Dunn2008_Dunn2008.phy; ../scripts/phylippart2multifasta.py -p phylips/Dunn2008_Dunn2008 -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Hejnol2009_Hejnol2009.phy; ../scripts/phylippart2multifasta.py -p phylips/Hejnol2009_Hejnol2009 -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Moroz2014_ED3a.phy; ../scripts/phylippart2multifasta.py -p phylips/Moroz2014_ED3a -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Moroz2014_ED3d.phy; ../scripts/phylippart2multifasta.py -p phylips/Moroz2014_ED3d -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Nosenko2013_nonribosomal_9187_smatrix.phy; ../scripts/phylippart2multifasta.py -p phylips/Nosenko2013_nonribosomal_9187_smatrix -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Nosenko2013_ribosomal_11057_smatrix.phy; ../scripts/phylippart2multifasta.py -p phylips/Nosenko2013_ribosomal_11057_smatrix -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Nosenko2013_ribosomal_14615_smatrix.phy; ../scripts/phylippart2multifasta.py -p phylips/Nosenko2013_ribosomal_14615_smatrix -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Philippe2009_Philippe2009.phy; ../scripts/phylippart2multifasta.py -p phylips/Philippe2009_Philippe2009 -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Ryan2013_est.opisthokonta.phy; ../scripts/phylippart2multifasta.py -p phylips/Ryan2013_est.opisthokonta -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Ryan2013_genome.opisthokonta.phy; ../scripts/phylippart2multifasta.py -p phylips/Ryan2013_genome.opisthokonta -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Simion2017_supermatrix_97sp_401632pos_1719genes.phy; ../scripts/phylippart2multifasta.py -p phylips/Simion2017_supermatrix_97sp_401632pos_1719genes -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Whelan2015_Dataset10_CertainPruned_LBAtaxa_LBAandHeteroGenesPruned.phy; ../scripts/phylippart2multifasta.py -p phylips/Whelan2015_Dataset10_CertainPruned_LBAtaxa_LBAandHeteroGenesPruned -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Whelan2015_Dataset1_FullData.phy; ../scripts/phylippart2multifasta.py -p phylips/Whelan2015_Dataset1_FullData -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Whelan2015_Datset20_Uncertain_LBAgenesHeteroRemoved_LBAtaxa.phy; ../scripts/phylippart2multifasta.py -p phylips/Whelan2015_Datset20_Uncertain_LBAgenesHeteroRemoved_LBAtaxa -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Whelan2017_Metazoa_Choano_RCFV_strict.phy; ../scripts/phylippart2multifasta.py -p phylips/Whelan2017_Metazoa_Choano_RCFV_strict -o queries -t ../taxonomy_info/taxon_table.tsv
echo phylips/Whelan2017_Metazoa_full.phy; ../scripts/phylippart2multifasta.py -p phylips/Whelan2017_Metazoa_full -o queries -t ../taxonomy_info/taxon_table.tsv
