---
output:
  html_document: default
  pdf_document: default
  word_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  dpi = 300,
  cache = FALSE
  )
```

```{r preliminaries}
  library( tidyverse )
  library( magrittr )
  library( gridExtra )

  source( "../phylobayes.R" )
  source( "../functions.R" )

  # A colorblind friendly palette from http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette:
  cbPalette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

  result_colors = c( cbPalette[2], cbPalette[4], cbPalette[1] )
  names( result_colors ) = c( "Ctenophora-sister", "Porifera-sister", "Unresolved" )
  
  aa = PartitionedMultipleAlignment ("../../data_processed/matrices/Whelan2017_strict.phy", "../../data_processed/matrices/Whelan2017_strict.nex")
  
  m = as.matrix(aa)
  site_occupancy = colSums(m != "-" ) / nrow(m)

```


An exploration of phylobayes chain samples.

```{r}

plot_chain = function( pb, site_occupancy ){

  allocation_counts = table(pb@allocation)
  index = allocation_counts %>% names() %>% as.numeric()
  
  if( ! all( index %in% rownames(pb@frequencies) ) ){
    stop("Allocations are outside available category range")
  }
  
  # Consider only the subset of frequencies that are allocated
  frequencies = pb@frequencies[ match(index , rownames(pb@frequencies) ), ]
  
  # Building on https://www.statmethods.net/advstats/mds.html
  d = dist( frequencies )
  fit = cmdscale(d,eig=TRUE, k=2)
  
  # Calculate the mean occupancy for each site in the original matrix
  occupancy = sapply( index, function(i){
    sites = which( pb@allocation == i  )
    mean( site_occupancy[ sites ] )
  })
  
  
  categories = 
    tibble(
      index = index,
      count = c(allocation_counts),
      occupancy = occupancy,
      x = fit$points[,1],
      y = fit$points[,2]
    ) %>%
    arrange(desc(count))
  
  categories %<>% mutate(rank = 1:nrow(categories))
  
  gg_mds = 
  categories %>% 
    ggplot() +
    geom_point(aes(x=x, y=y, size=count), alpha=0.4 ) +
    ggtitle("MDS plot of frequency categories") +
    theme_classic()
  
  
  gg_rank = 
    categories %>%
    ggplot() +
      geom_point(aes(x=rank, y=cumsum(count)) ) +
      ggtitle("Cumulative sum of sites") +
      theme_classic()
  
  p = grid.arrange(
  	gg_rank,
  	gg_mds,
  	ncol = 2
  )
  
  return(p)
}


```




```{r}

chain = parse_phylobayes_chain( "../tests/testthat/example.chain" )
  
# Take just the last sample for now
pb = chain[[length(chain)]]

plot_chain( pb, site_occupancy )

```

**Figure n60.** Plots for nCAT=60.


```{r}

chain = parse_phylobayes_chain( "Whelan2017_strict.phy_Poisson_CAT100_Chain_1_last500.chain" )
  
# Take just the last sample for now
pb = chain[[length(chain)]]

plot_chain( pb, site_occupancy )

```

**Figure n100.** Plots for nCAT=100.

```{r}

chain = parse_phylobayes_chain( "Whelan2017_strict.phy_Chain1_last50000.chain" )
  
# Take just the last sample for now
pb = chain[[length(chain)]]

plot_chain( pb, site_occupancy )

```

**Figure CAT.** Plots for CAT.

