#!/bin/bash
sed -i 's/AMAC______/Allomyces_macrogynus/' *.phy
sed -i 's/AFUM______/Aspergillus_fumigatus/' *.phy
sed -i 's/MVER______/Mortierella_verticillata/' *.phy
sed -i 's/ASPE______/Acanthoeca_spectabilis/' *.phy
sed -i 's/NCRA______/Neurospora_crassa/' *.phy
sed -i 's/RORY______/Rhizopus_oryzae/' *.phy
sed -i 's/SCER______/Saccharomyces_cerevisiae/' *.phy
sed -i 's/SPUN______/Spizellomyces_punctatus/' *.phy
sed -i 's/APAR______/Amoebidium_parasiticum/' *.phy
sed -i 's/COWC______/Capsaspora_owczarzaki/' *.phy
sed -i 's/MVIB______/Ministeria_vibrans/' *.phy
sed -i 's/SARC______/Sphaeroforma_arctica/' *.phy
sed -i 's/MBRE______/Monosiga_brevicollis/' *.phy
sed -i 's/MOVA______/Monosiga_ovata/' *.phy
sed -i 's/SPYX______/Salpingoeca_pyxidium/' *.phy
sed -i 's/SROS______/Salpingoeca_rosetta/' *.phy
sed -i 's/TADH______/Trichoplax_adhaerens/' *.phy
sed -i 's/ATRA______/Acropora_digitifera/' *.phy
sed -i 's/ATET______/Abylopsis_tetragona/' *.phy
sed -i 's/BTUE______/Bolocera_tuediae/' *.phy
sed -i 's/AELE______/Agalma_elegans/' *.phy
sed -i 's/NBIJ______/Nanomia_bijuga/' *.phy
sed -i 's/APAL______/Aiptasia_pallida/' *.phy
sed -i 's/AAUR______/Aurelia_aurita/' *.phy
sed -i 's/CHEM______/Clytia_hemisphaerica/' *.phy
sed -i 's/EVER______/Eunicella_verrucosa/' *.phy
sed -i 's/GANT______/Gersemia_antarctica/' *.phy
sed -i 's/HOLI______/Hydra_oligactis/' *.phy
sed -i 's/HVIR______/Hydra_viridissima/' *.phy
sed -i 's/HDIG______/Hormathia_digitata/' *.phy
sed -i 's/HVUL______/Hydra_vulgaris/' *.phy
sed -i 's/NVEC______/Nematostella_vectensis/' *.phy
sed -i 's/PPER______/Periphylla_periphylla/' *.phy
sed -i 's/PPHY______/Physalia_physalis/' *.phy
sed -i 's/PCAR______/Platygyra_carnosa/' *.phy
sed -i 's/CLAT______/Craseoa_lathetica/' *.phy
sed -i 's/AQUE______/Amphimedon_queenslandica/' *.phy
sed -i 's/AVAS______/Aphrocallistes_vastus/' *.phy
sed -i 's/CNUC______/Chondrilla_nucula/' *.phy
sed -i 's/CCAN______/Corticium_candelabrum/' *.phy
sed -i 's/CELE______/Crella_elegans/' *.phy
sed -i 's/EMUE______/Ephydatia_muelleri/' *.phy
sed -i 's/HPOP______/Hyalonema_populiferum/' *.phy
sed -i 's/IFAS______/Ircinia_fasciculata/' *.phy
sed -i 's/KVAR______/Kirkpatrickia_variolosa/' *.phy
sed -i 's/LAPI______/Latrunculia_apicalis/' *.phy
sed -i 's/OCAR______/Oscarella_carmela/' *.phy
sed -i 's/PFIC______/Petrosia_ficiformis/' *.phy
sed -i 's/PSUB______/Pseudospongosorites_suberitoides/' *.phy
sed -i 's/RFIB______/Rossella_fibulata/' *.phy
sed -i 's/SLAC______/Spongilla_alba/' *.phy
sed -i 's/STRA______/Sycon_ciliatum/' *.phy
sed -i 's/SCOA______/Sycon_coactum/' *.phy
sed -i 's/SNUX______/Sympagella_nux/' *.phy
sed -i 's/TWIL______/Tethya_wilhelma/' *.phy
sed -i 's/BABY______/Beroe_abyssicola/' *.phy
sed -i 's/BINF______/Bolinopsis_infundibulum/' *.phy
sed -i 's/CAST______/Coeloplana_astericola/' *.phy
sed -i 's/DGLA______/Dryodora_glandiformis/' *.phy
sed -i 's/EDUN______/Euplokamis_dunlapae/' *.phy
sed -i 's/MSPP______/Mertensiidae_sp/' *.phy
sed -i 's/MLEI______/Mnemiopsis_leidyi/' *.phy
sed -i 's/PTRA______/Pleurobrachia_bachei/' *.phy
sed -i 's/PATL______/Pleurobrachia_atlantica/' *.phy
sed -i 's/VALL______/Vallicula_sp/' *.phy
sed -i 's/HSAP______/Homo_sapiens/' *.phy
sed -i 's/DRER______/Danio_rerio/' *.phy
sed -i 's/PMAR______/Petromyzon_marinus/' *.phy
sed -i 's/SKOW______/Saccoglossus_kowalevskii/' *.phy
sed -i 's/SPUR______/Strongylocentrotus_purpuratus/' *.phy
sed -i 's/CTEL______/Capitella_teleta/' *.phy
sed -i 's/HPSI______/Hemithiris_psittacea/' *.phy
sed -i 's/LGIG______/Lottia_gigantea/' *.phy
sed -i 's/TPOL______/Tubulanus_polymorphus/' *.phy
sed -i 's/DPUL______/Daphnia_pulex/' *.phy
sed -i 's/DMEL______/Drosophila_melanogaster/' *.phy
sed -i 's/PSPP______/Priapulus_caudatus/' *.phy
sed -i 's/LITH______/Lithobius_forficatus/' *.phy



